name: Deploy on Allegheny CIS infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26.7.0
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs/

      - name: Build site
        working-directory: website
        run: npm run build

      - name: Archive site
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: website
          path: website/dist

      - name: Deploy
        uses: burnett01/rsync-deployments@9.0.0
        with:
          switches: -avz --delete
          path: website/dist/
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}
