name: Deploy on Allegheny CIS infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Build site
        working-directory: website
        run: npm run build

      - name: Deploy
        uses: burnett01/rsync-deployments@9.0.0
        with:
          switches: -avz --delete
          path: website/dist/
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}
